import { Poppins } from 'next/font/google';

import './globals.css';
import { NextAuthProvider } from './providers';

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin-ext'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={poppins.className + ' bg-slate-50 min-h-screen'}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
